feature/OAuth2
free5gc/udm pull request #33
Opened 2024-01-23 05:45 UTC by a3828162

- [x] Use Middleware for authorization
- [x] Consumer retrieve token
- [x] Replace the service name in each HTTP request of the producer with the OpenAPI name
- [x] Complete unit test of router_auth_check_test.go

2024-01-23 10:48 UTC, ianchen0119 commented on internal/sbi/producer/generate_auth_data.go
> +	// rsp, err = client.AuthenticationDataDocumentApi.ModifyAuthentication(
please remove commented code

2024-01-23 10:49 UTC, ianchen0119 commented on internal/sbi/producer/parameter_provision.go
> +// const serviceName string = string(models.ServiceName_NUDR_DR)
please remove commented code

2024-01-23 10:49 UTC, ianchen0119 commented on internal/sbi/producer/subscriber_data_management.go
> +		// smfSelData, res, err := clientAPI.SMFSelectionSubscriptionDataDocumentApi.QuerySmfSelectData(context.Background(),
please remove commented code

2024-01-23 10:49 UTC, ianchen0119 commented on internal/sbi/producer/subscriber_data_management.go
> +		// pdusess, res, err := clientAPI.SMFRegistrationsCollectionApi.QuerySmfRegList(
please remove commented code

2024-01-23 10:50 UTC, ianchen0119 commented on internal/sbi/producer/subscriber_data_management.go
> +		// sessionManagementSubscriptionData, res, err := clientAPI.SessionManagementSubscriptionDataApi.
please remove commented code

2024-01-23 10:50 UTC, ianchen0119 commented on internal/sbi/producer/subscriber_data_management.go
> +		// traceData, res, err := clientAPI.TraceDataDocumentApi.QueryTraceData(
please remove commented code

2024-01-23 11:00 UTC, ianchen0119 requested changes
Hi @a3828162 
Please update the patch base on my comments.
Thanks.

2024-02-02 05:48 UTC, andy89923 approved these changes
LGTM!

2024-02-05 15:48 UTC, tim-ywliu commented on internal/util/util.go
> +	NfTypeNRF = models.NfType_NRF
no need to define const again, directly use models

2024-02-05 15:51 UTC, tim-ywliu commented on internal/util/util.go
> +	ServiceNameNnrfDisc = string(models.ServiceName_NNRF_DISC)
no need to define const again, directly use `string(models.ServiceNAme_xxx)`

2024-02-07 07:18 UTC, ianchen0119 approved these changes

2024-02-07 07:18 UTC, merged