refactor
free5gc/udm pull request #37
Opened 2024-05-08 09:02 UTC by a3828162

- [x] consumer finish
- [x] api_{SVC}.go
- [x] processor
- [ ] server
- [ ] router

2024-05-15 05:06 UTC, ianchen0119 commented
Hi @a3828162 

Please help to resolve the conflicts in `pkg/service/init.go`.
Tks!

2024-05-23 12:09 UTC, yccodr commented on pkg/service/init.go
> +	logger.MainLog.Infof("CHF SBI Server terminated")
@a3828162 Hello?

2024-05-24 02:12 UTC, ianchen0119 commented on cmd/main.go
> +	UDM.WaitRoutineStopped()
`udm.WaitRoutineStopped()`

2024-05-24 02:16 UTC, ianchen0119 commented on internal/sbi/consumer/nf_management_test.go
> +	//_, _, err := SendRegisterNFInstance("http://127.0.0.10:8000", "1", models.NfProfile{})
Why did you change the unit test?

2024-05-24 02:24 UTC, ianchen0119 commented on internal/sbi/eventexposure/api_create_ee_subscription.go
> +	var eesubscription models.EeSubscription
Please also check on these folders:
![image](https://github.com/free5gc/udm/assets/42661015/60d6b884-17c9-48c6-83c7-f6879469ee5b)

2024-05-24 02:41 UTC, ianchen0119 commented on cmd/main.go
>  	UDM = udm
This line is duplicated (please see `NewApp()`).

2024-06-04 05:44 UTC, andy89923 commented on internal/sbi/processor/processor.go
> +}
I thinks we don't need this.

2024-06-04 05:44 UTC, andy89923 commented on internal/sbi/router.go
> +func AddSDMService(group *gin.RouterGroup, routes []Route) {
.

2024-06-04 05:44 UTC, andy89923 commented on internal/sbi/router.go
> +func AddUEAUService(group *gin.RouterGroup, routes []Route) {
.

2024-06-04 05:44 UTC, andy89923 commented on internal/sbi/router.go
> +func AddService(group *gin.RouterGroup, routes []Route) {
.

2024-06-04 05:44 UTC, andy89923 commented on internal/sbi/router.go
> +func AddSDMService(group *gin.RouterGroup, routes []Route) {
.

2024-06-04 05:44 UTC, andy89923 commented on internal/sbi/router.go
> +func AddUEAUService(group *gin.RouterGroup, routes []Route) {
.

2024-06-04 05:44 UTC, andy89923 commented on pkg/service/init.go
> +
remove

2024-06-12 07:00 UTC, ming-hsien commented on internal/sbi/consumer/nrf_service.go
> +		// Todo
I think we can delete the unnecessary code.

2024-06-21 04:40 UTC, andy89923 reviewed
Also, need to fix the Termination procedure; you could refer to the Discord message.

2024-06-21 04:40 UTC, andy89923 commented on pkg/service/init.go
> +	sbi.ServerUdm
remove, we don't need this

2024-06-21 04:40 UTC, andy89923 commented on internal/sbi/consumer/nrf_service.go
> +		defer s.nfMngmntMu.RUnlock()
no defer
```suggestion
		s.nfMngmntMu.RUnlock()
```

2024-06-21 04:40 UTC, andy89923 commented on internal/sbi/consumer/nrf_service.go
> +		defer s.nfMngmntMu.RUnlock()
so as others

2024-06-22 15:13 UTC, andy89923 commented on internal/sbi/server.go
> +	logger.SBILog.Warnf("SBI server (listen on %s) stopped", s.httpServer.Addr)
suggest log level to info

2024-06-22 15:13 UTC, andy89923 commented on internal/sbi/server.go
> +		routerAuthorizationCheck.Check(c, udm_context.GetSelf())
```suggestion
		routerAuthorizationCheck.Check(c, s.Context())
```

2024-06-22 15:13 UTC, andy89923 commented on internal/sbi/processor/callback.go
`callback` rename to `notifier`

2024-06-22 15:13 UTC, andy89923 commented on internal/sbi/api_uecontextmanagement.go
> +	c.JSON(http.StatusOK, gin.H{})
This could also change to http.NotImplement

2024-06-25 01:57 UTC, ianchen0119 commented on internal/sbi/server.go
> +	logger.SBILog.Info("SBI server (listen on %s) stopped", s.httpServer.Addr)
Use `Infof` instead.

2024-06-25 02:07 UTC, ianchen0119 commented on internal/sbi/processor/enent_exposure.go
> -package producer
`xxx_enent` -> `xxx_event.go`

2024-06-25 02:17 UTC, ianchen0119 requested changes
Please ensure the implementations of processor pkg follow our standard.

2024-06-25 10:30 UTC, andy89923 commented on internal/sbi/processor/ue_context_management.go
>  	request *models.SmfRegistration,
`request` rename to `smfRegistration`

2024-06-25 10:33 UTC, andy89923 commented on internal/sbi/processor/ue_context_management.go
> +		}
I think we will have "Location" only in the header

2024-06-26 06:14 UTC, andy89923 commented on internal/sbi/api_parameterprovision.go
> +	gpsi := c.Params.ByName("gpsi")
```go
gpsi := c.Params.ByName("gpsi")
if gpsi == "" {
  problem := ...
  
  C.JSON()
  return
}
```

2024-06-26 06:14 UTC, andy89923 commented on internal/sbi/api_subscriberdatamanagement.go
> +	c.JSON(http.StatusOK, gin.H{})
NotImplement

2024-06-26 06:14 UTC, andy89923 commented on internal/sbi/api_subscriberdatamanagement.go
> +	c.JSON(http.StatusOK, gin.H{})
NotImplement

2024-06-26 06:14 UTC, andy89923 commented on internal/sbi/api_subscriberdatamanagement.go
> +	// step 1: log
remove

2024-06-26 06:14 UTC, andy89923 commented on internal/sbi/api_subscriberdatamanagement.go
> +	// step 1: log
remove all unnecessary comment message

2024-06-26 17:22 UTC, andy89923 approved these changes

2024-06-27 05:53 UTC, ianchen0119 commented on internal/sbi/processor/processor.go
> +func NewProcessor(udm ProcessorUdm) (*Processor, error) {
Please refer to https://github.com/free5gc/amf/pull/132/files

You don't need to implement the Consumer getter here.

2024-06-27 05:54 UTC, ianchen0119 reviewed
LGTM (except for my commented part)

2024-06-27 08:29 UTC, merged